### ISSUE TITLE
(IOS)(ANDRIOD)(BUG) Able to make order when api call for price is disconnected 

### ISSUE THREAD

**Issue by douglasswm** [coinotc/coinotc-kitchensink#103]
![6ab9db2d-f2de-4dd3-a729-f029039b06ad](https://user-images.githubusercontent.com/20721915/38164525-9baaba3e-3538-11e8-8b08-edddf0f8e882.png)
![4c78a818-6960-4a2a-89c3-e7026518a555](https://user-images.githubusercontent.com/20721915/38164526-9c03941a-3538-11e8-95d8-86da621188dc.png)

**Comment by shetz163** [comment]
![snipaste_2018-04-03_17-26-28](https://user-images.githubusercontent.com/5582519/38241184-28a1f9d4-3764-11e8-85ec-cb5ce1e12f91.png)
