### ISSUE TITLE
Double click me error gettting some random link ?

### ISSUE THREAD

**Issue by kenken64** [coinotc/coinotc-kitchensink#74]
![image](https://user-images.githubusercontent.com/631205/38044718-2ba35324-32ed-11e8-9173-8131f5f90ebe.png)

i.ytimg.com/vi/eUxQnXunpmA/maxresdefault.jpg:1 GET https://i.ytimg.com/vi/eUxQnXunpmA/maxresdefault.jpg net::ERR_CONNECTION_TIMED_OUT
Image (async)
DefaultDomRenderer2.insertBefore @ vendor.js:45755
BaseAnimationRenderer.insertBefore @ vendor.js:144852
DebugRenderer2.insertBefore @ vendor.js:15288
execRenderNodeAction @ vendor.js:10346
visitRenderNode @ vendor.js:10317
visitSiblingRenderNodes @ vendor.js:10248
visitRootRenderNodes @ vendor.js:10232
renderAttachEmbeddedView @ vendor.js:11180
attachEmbeddedView @ vendor.js:11060
ViewContainerRef_.insert @ vendor.js:11531
NavControllerBase._viewAttachToDOM @ vendor.js:58925
Tab._viewAttachToDOM @ vendor.js:105107
NavControllerBase._transition @ vendor.js:59013
(anonymous) @ vendor.js:58734
t.invoke @ polyfills.js:3
onInvoke @ vendor.js:4983
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
(anonymous) @ polyfills.js:3
t.invokeTask @ polyfills.js:3
onInvokeTask @ vendor.js:4974
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
o @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
error (async)
O @ polyfills.js:2
t.scheduleTask @ polyfills.js:3
onScheduleTask @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleEventTask @ polyfills.js:3
(anonymous) @ polyfills.js:2
(anonymous) @ vendor.js:84383
Observable._trySubscribe @ vendor.js:19905
Observable.subscribe @ vendor.js:19893
CatchOperator.call @ vendor.js:154151
Observable.subscribe @ vendor.js:19890
MapOperator.call @ vendor.js:77252
Observable.subscribe @ vendor.js:19890
MapOperator.call @ vendor.js:77252
Observable.subscribe @ vendor.js:19890
webpackJsonp.152.AuthPage.submitForm @ main.js:738
(anonymous) @ AuthPage.html:33
handleEvent @ vendor.js:13609
callWithDebugContext @ vendor.js:15094
debugHandleEvent @ vendor.js:14681
dispatchEvent @ vendor.js:10058
(anonymous) @ vendor.js:12382
schedulerFn @ vendor.js:4589
SafeSubscriber.__tryOrUnsub @ vendor.js:21999
SafeSubscriber.next @ vendor.js:21946
Subscriber._next @ vendor.js:21886
Subscriber.next @ vendor.js:21850
Subject.next @ vendor.js:50476
EventEmitter.emit @ vendor.js:4557
FormGroupDirective.onSubmit @ vendor.js:30125
(anonymous) @ AuthPage.html:33
handleEvent @ vendor.js:13609
callWithDebugContext @ vendor.js:15094
debugHandleEvent @ vendor.js:14681
dispatchEvent @ vendor.js:10058
(anonymous) @ vendor.js:10672
(anonymous) @ vendor.js:45608
t.invokeTask @ polyfills.js:3
onInvokeTask @ vendor.js:4974
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
i.ytimg.com/vi/Yj7ja6BANLM/maxresdefault.jpg:1 GET https://i.ytimg.com/vi/Yj7ja6BANLM/maxresdefault.jpg net::ERR_CONNECTION_TIMED_OUT

**Comment by douglasswm** [comment]
Images are from Google Images. Turn On VPN to solve the issue.
